- src/test_rp/op/htdocs/rp_test_list.mako
- src/test_rp/op/pathmap.py
- src/test_rp/op/static/rp_test_list.js
- src/test_rp/rp/cflows.py
Have been synchronizing test names in test implementation and the documentation. Also added new tests to the doc
> sync name + added more tests

- src/test_rp/op/htdocs/rp_test_list.mako
- src/test_rp/op/static/rp_test_list.js
Added profiles to the test doc. Made it possible to only show test a specific profile
> Added profiles

- src/oidctest/session.py
- src/oidctest/tool.py
- src/test_rp/rp/cl/clrp.py
> Revert "Can now have multiple settings tests"

- test_tool/test_rp/op/static/rp_test_list.js
Correct "profiles" values for hybrid response_type tests to be [HYBRID].
> Move hybrid response_type tests to HYBRID profile

- src/oidctest/rp/test_config.py
allows
- code+id_token/rp-id_token-bad-at_hash
- code+token/rp-id_token-bad-at_hash
- code+token/rp-id_token-bad-c_hash
- code+token/rp-token_endpoint-client_secret_basic
- id_token+token/rp-token_endpoint-client_secret_basic
> added more allowed response_types

- .gitignore
- docs/maintenance.md
- src/oidctest/cp/op.py
this requires a related patch to pyoidc's webfinger implementation
> correct rp-discovery-webfinger-unknown-member implementation

- docs/maintenance.md
- test_tool/cp/test_op/run_example.sh
> update docs to new-rp/new-op; add kill & restart to run_example.sh

- test_tool/cp/test_rplib/rp/run_example.sh
> also add improved run_example.sh for RP testing

- docs/maintenance.md
> add notes about rolling over the SSL server certificate

- src/oidctest/tt/fed.py
> fix imports previously from oic.oauth2

- README.md
> add Travis CI docs to README.md

- tests/flows/OP-nonce-NoReq-noncode.json
> add MTI to OP-nonce-NoReq-noncode; certification/oidctest#14

- test_tool/cp/test_op/config_server.py
- test_tool/cp/test_op/op_test_tool.py
- test_tool/cp/test_rplib/rp/server.py
change default CherryPy icon to an OIDF icion
> use OIDF favicon

- docker/op/Dockerfile
- src/oidctest/ass_port.py
addresses openid-certification/oidctest#35 for new registrations
> deal with double port assignments and out-of-band ports

- src/oidctest/tt/entity.py
> fix display of URL-unsafe tags; see openid-certification/oidctest#35

- .gitattributes
- test_tool/cp/test_op/config_server.py
- test_tool/cp/test_op/op_test_tool.py
- test_tool/cp/test_rplib/rp/server.py
- test_tool/cp/test_rplib/rp/static/robots.txt
close openid-certification/oidctest#37 and avoid robots crawling the test servers and polluting the logs
> add .gitattributes openid-certification/oidctest#37 and robots.txt

- docs/extension.md
> add extension.md doc, version 0.1 beta

- .travis.yml
> use master branch for op tests

- docker/op_test/Dockerfile
- docker/op_test/pyoidc.patch
> add pyoidc patch back for 0.12.0

- src/oidctest/op/check.py
> don't copy error status

- src/oidctest/tt/action.py
addresses openid-certification/oidctest#53
> kill running process before deleting config

- src/oidctest/tt/action.py
address openid-certification/oidctest#26 and openid-certification/oidctest#56
> Require contact email and https issuer

- test_tool/cp/test_rplib/rp/flows/rp-3rd_party-init-login.json
> html-encode detailed description

- test_tool/cp/test_op/flows/OIDC/OP-request-Unsigned.json
- test_tool/cp/test_op/flows/OP-request_uri-Unsigned.json
see openid-certification/oidctest#67
> change registered sigalg in OP-request_uri-Unsigned to "none"

- src/oidctest/op/check.py
- test_tool/cp/test_op/flows/OP-Discovery-Config.json
see openid-certification/oidctest#71
> verify that RS256 is in id_token_signing_alg_values_supported

- src/oidctest/cp/op.py
> fix typo in setting content type header

- .travis.yml
- docker/docker-compose.yml
- setup.py
- src/oidctest/op/client.py
- src/oidctest/rp/provider.py
- test_tool/cp/test_op/op_test_tool.py
- test_tool/cp/test_rplib/rp/server.py
which changed to response.status_code in pyoidc >= 0.14.0
> Fix response status and verify param

- test_tool/cp/test_op/flows/OP-OAuth-2nd-30s.json
- test_tool/cp/test_op/flows/OP-OAuth-2nd-Revokes.json
- test_tool/cp/test_op/flows/OP-OAuth-2nd.json
see openid-certification/oidctest#99
> correct OAuth behavior test descriptions

- test_tool/cp/test_op/flows/OP-Rotation-OP-Sig.json
see: openid-certification/oidctest#102
> add OP-Rotation-OP-Sig to "register" profile instead of "discover"

- src/oidctest/tt/action.py
see: openid-certification/oidctest#112
> add redirect_uri instructions for form_post

- tests/test_20_session.py
> fix unit tests

- src/oidctest/tt/action.py
see: openid-certification/oidctest#75
> complete configuration help tooltips

- docs/maintenance.md
Version 2.1.0 - October 2, 2018
> improve release management docs based on Filip's feedback

- test_tool/cp/test_op/flows/OP-3rd_party-init-login-nohttps.json
- test_tool/cp/test_op/flows/OP-3rd_party-init-login.json
see openid-certification/oidctest#129
> add OP-3rd_party-init-login and OP-3rd_party-init-login-nohttps

- src/oidctest/op/oper.py
Previous code changes were overwritten during merging. Re-adding the try except block
> Re-adding the missing code changes for issue 7.

- setup.py
- src/oidctest/op/func.py
- tests/test_12_op_func.py
Close https://github.com/openid-certification/oidctest/issues/145
> Fix comparison of types in check_support

- setup.py
> update to pyoidc 0.15.1

- test_tool/cp/test_op/flows/OP-redirect_uri-Query-Mismatch.json
correct typo; 2nd attempt because the first got lost
> fix OP-redirect_uri-Query-Mismatch openid-certification#189
