rohe/oidctest

- test_tool/test_rp/rplib/op/static/rp_test_list.js
Added rp-id_token-sig-rs256 to "profiles": [BASIC_OPTIONAL, IMPLICIT, HYBRID, SELF_ISSUED].
Added rp-id_token-iat to SELF_ISSUED.
Changed case of two spellings of "Self-Issued" in message strings.
> Tweak which profiles two tests occur in

- test_tool/cp/test_rplib/rp/flows/rp-id_token-bad-c_hash.json
remove (optional) flows that don't return an id_token in the
frontchannel; the test server would not return a (bad) c_hash in these
flows anyway
> remove "code" and "code token" profiles from rp-id_token-bad-c_hash

- src/oidctest/op/check.py
since it was renamed to get_authorization_request in otest
> fix reference to non-existing get_protocol_request

- test_tool/cp/test_op/flows/OP-prompt-none-NotLoggedIn.json
add the acceptable error messages from the assertion to the expected
error messages for AsyncAuthn otherwise the response test will be
aborted before reaching the assertion
> add assertion errors to AsyncAuthn as well

- .travis.yml
- src/oidctest/tt/action.py
- remove duplicate (2x) "stop" operations from action.py
- switch back to new-op branch from openid-certification repo for the
oidc-provider-conformance-tests CI tests
> remove leftovers from merging bootstrap

- test_tool/cp/test_rplib/rp/flows/rp-id_token-kid-absent-single-jwks.json
addresses openid-certification/oidctest#29
> improve description for rp-id_token-kid-absent-single-jwks

- setup.py
until phone_number_verified claim type checking is fixed
see: https://github.com/OpenIDC/pyoidc/issues/407
> fix pyoidc to 0.10.0

- src/oidctest/op/check.py
OP-prompt-login shouldn't depend on "auth_time" since it is not a
required claim. Do issue a warning. See: openid-certification/oidctest#36
> don't require `auth_time` in id_token for `OP-prompt-login`

- src/oidctest/op/check.py
a Warning may not be the best outcome as the test may still pass if the screenshot is OK
> openid-certification/oidctest#36 needs more discussion

- README.md
- test_tool/cp/test_op/version.py
- test_tool/cp/test_rplib/rp/version.py
- so new-op/new-rp will no longer display the release numbers
2.0.0/1.0.0
- also make testers use the stable branch for the Dockerized version of
the suite
> display "dev" for the version in the master branch

- src/oidctest/rp/provider.py
addresses the 2nd half of openid-certification/oidctest#26
caveat emptor: this change may break some automation tools that don't provide this information (yet)... oh well
> require e-mail address for RP testers at registration time

- src/oidctest/cp/op.py
- src/oidctest/rp/provider.py
- test_tool/cp/test_rplib/rp/config.py
- test_tool/cp/test_rplib/rp/example_conf.py
- test_tool/cp/test_rplib/rp/flows/rp-3rd_party-init-login.json
- test_tool/cp/test_rplib/rp/server.py
no GUI, triggered by calling:
https://<rp_test_host>:<rp_test_port>/rp/<rp_id>/rp-3rd_party-init-login/<client_id>
for a registered client/rp instance
@rohe: please review; this should also setup basic handling for adding additional tests in the future with a GUI displayed for a specific rp_id and/or client_id and/or test_id
> add 3rd-party-init-sso test

- test_tool/cp/test_op/flows/OIDC/OP-Rotation-RP-Enc.json
- test_tool/cp/test_op/flows/OIDC/OP-UserInfo-Enc.json
- test_tool/cp/test_op/flows/OIDC/OP-request_uri-Enc.json
- test_tool/cp/test_op/flows/OIDC/OP-request_uri-Unsigned.json
- test_tool/cp/test_op/flows/OP-Rotation-RP-Enc.json
- test_tool/cp/test_op/flows/OP-UserInfo-Enc.json
- test_tool/cp/test_op/flows/OP-request-Unsigned.json
- test_tool/cp/test_op/flows/OP-request_uri-Enc.json
see openid-certification/oidctest#69
- for OP-request-Unsigned set request_object_signing_alg to "none" (as
in #67)
- for OP-request_uri-Enc remove request_object_signing_alg from the
registration request
- for OP-UserInfo-Enc and OP-Rotation-RP-Enc remove
userinfo_signed_response_alg from the registration request
> avoid sending null values in dynamic client registration

- docker/op_test/Dockerfile
- test_tool/cp/test_op/flows/OP-Response-form_post.json
support for form_post profile was added in otest 0.7.3/master; add
OP-response-form_post to that profile
use pyoidc master commit checkout to support:
- return RegistrationError on missing required attribute; see:
openid-certification/oidctest#70
- allow endpoints to have query parts; see
openid-certification/oidctest#74
- log the registration request, see openid-certification/oidctest#38
- audience is endpoint dependent; see openid-certification/oidctest#21
> use unreleased pyoidc; add OP-response-form_post to form_post profile

- test_tool/cp/test_op/flows/OP-Response-form_post.json
since it is in its own form_post profile now
> OP-Response-form_post no longer needs to be extra

- docker/op_test/Dockerfile
when using basic auth; see openid-certification/oidctest#61
> use pyoidc commit that doesn't send client_id in token requests

- src/oidctest/cp/op.py
see: openid-certification/oidctest#78
> don't overwrite content-type for the userinfo response

- test_tool/cp/test_rplib/rp/flows/rp-response_mode-form_post.json
add it to the "code" response type as well; see
openid-certification/oidctest#100
> make form_post response mode available in all response types

- test_tool/cp/test_op/flows/OP-Error-form_post.json
- test_tool/cp/test_op/flows/OP-Response-Missing.json
- test_tool/cp/test_op/flows/OP-Response-code+id_token+token.json
- test_tool/cp/test_op/flows/OP-Response-code+id_token.json
- test_tool/cp/test_op/flows/OP-Response-code+token.json
- test_tool/cp/test_op/flows/OP-Response-code.json
- test_tool/cp/test_op/flows/OP-Response-form_post-Error.json
- test_tool/cp/test_op/flows/OP-Response-form_post.json
- test_tool/cp/test_op/flows/OP-Response-id_token+token.json
- test_tool/cp/test_op/flows/OP-Response-id_token.json
- tests/flows/OP-Response-Missing.json
- tests/flows/OP-Response-code+id_token+token.json
- tests/flows/OP-Response-code+id_token.json
- tests/flows/OP-Response-code+token.json
- tests/flows/OP-Response-code.json
- tests/flows/OP-Response-form_post.json
- tests/flows/OP-Response-id_token+token.json
- tests/flows/OP-Response-id_token.json
- renamed the form post test to follow the existing convention
- added a missing Note to the error form post test
- split "Response Type & Response Mode" into two categories and moved the tests accordingly
- see https://github.com/openid-certification/otest/pull/2 for the categories being defined in otest
> form post error test and categories split

- docker/op/Dockerfile
- docs/maintenance.md
- add release process steps to maintenance doc
- upgrade CI OP node-oidc-provider from version 3.0.1 to 4.0.3
> update maintenance documentation and upgrade CI OP version

- src/oidctest/tt/action.py
see also: https://github.com/openid-certification/oidctest/pull/118
> html-encode redirect URI value since it is multi-value now

- src/oidctest/rp/provider.py
- test_tool/cp/test_rplib/rp/flows/rp-response_mode-form_post-error.json
- improve the test description on how to trigger an error
- allow for authentication requests that don't have a `state` parameter
- see openid-certification/oidctest#132
> improve rp-response_mode-form_post-error; see #132

- src/oidctest/op/check.py
a MissingRequiredAttribute error is properly progated from otest but
then the final assertion handler `check-idtoken-nonce` that verifies the
nonce is not prepared to deal with an invalid - and missing - id_token
see: openid-certification/oidctest/issues/124
> fix error handling when c_hash is missing in Implicit/Hybrid flows

- docs/maintenance.md
record that we're going to use force push on
oidc-provider-conformance-tests updates which should not hurt anyone
> update release management doc for oidc-provider-conformance-tests

- src/oidctest/app_conf.py
- src/oidctest/tt/app.py
shell escape "iss" and "tag" values (provided by configuration) before
passing those values to os.system calls
> fix remote execution security vulnerability

- src/oidctest/op/oper.py
- test_tool/cp/test_op/flows/OP-OAuth-2nd-30s.json
- test_tool/cp/test_op/flows/OP-OAuth-2nd.json
- tests/flows/OP-OAuth-2nd-30s.json
- tests/flows/OP-OAuth-2nd.json
I added a try-except to prevent abrupt failures when response code is unexpected. Also added http response code checks to OP-OAuth-2nd and OP-OAuth-2nd-30s.
How to test it: 
- Run `docker exec -it docker_op_1 /bin/bash`
- Edit `./lib/helpers/errors.js`:  and change status code to 403, e.g:  
```super(403, 'invalid_grant');```
- Stop and restart (do not rebuild) docker_op_1. 
- Run https://op-test:60003/OP-OAuth-2nd and https://op-test:60003/OP-OAuth-2nd-30s
@rohe OP-OAuth-2nd-30s returns an error status while OP-OAuth-2nd returns a warning in case of an invalid_grant response. Should they be consistent? I can add another commit if we would like to make them consistent. Let me know if any additional changes are needed.
> oidctest Issue #7. 

- src/oidctest/op/func.py
- src/oidctest/op/oper.py
- test_tool/cp/test_op/flows/OP-ClientAuth-Basic-Dynamic.json
- test_tool/cp/test_op/flows/OP-ClientAuth-PrivateJWT.json
- test_tool/cp/test_op/flows/OP-ClientAuth-SecretJWT.json
- test_tool/cp/test_op/flows/OP-ClientAuth-SecretPost-Dynamic.json
- tests/flows/OP-ClientAuth-Basic-Dynamic.json
- tests/flows/OP-ClientAuth-PrivateJWT.json
- tests/flows/OP-ClientAuth-SecretJWT.json
- tests/flows/OP-ClientAuth-SecretPost-Dynamic.json
I added checks to make sure that a mutually supported token endpoint authn method is used. Also updated some test flows and added checks to make sure that the required client authentication method is supported.
OP-ClientAuth-Basic-Static and OP-ClientAuth-Basic-Dynamic now return PARTIAL_RESULT with "No support for: token_endpoint_auth_methods_supported=client_secret_basic" error when client_secret_basic method is not supported. We should clarify if they should return a failure or not. 
How I tested it : 
- I used the node-oidc-provider
- I edited example/setttings.js to enable/disable specific client authentication methods and to create static clients. For example : 
```
...
module.exports.config = {
tokenEndpointAuthMethods: ['private_key_jwt'],	//<<<add this line
acrValues: …
```
> Issue #142. 

- setup.py
pyoidc 0.15.0 breaks encrypted JWTs.
> Fix pyoidc version to 0.14.0

- src/oidctest/op/client.py
Prevent exceptions cause by 401 responses without a json body. 
WWW-Authenticate header is not parsed but added as a whole to error_description.
> oidctest issue 116

- test_tool/cp/test_op/flows/OP-nonce-NoReq-noncode.json
Change OP-nonce-NoReq-noncode to allow an error response returned from
the OP to the test suite without an intermediate screen displaying
(wrong) text.
- correct the note text about only the OP allowed to display an error
- the test suite also allows the OP to return "invalid_request" or
similar returned in a redirect
- remove CT from MTI (previously omitted)
> address openid-certification/oidctest#144

- test_tool/cp/test_op/flows/OP-redirect_uri-Query-Mismatch.json
address openid-certification/oidctest#189
> the previous patch apparently swapped the syntax between reg and auth
